//Check Plugins
if(!`pluginInfo -q -l "fbxmaya"`)
	loadPlugin "fbxmaya";

global string $MassFbxLayer = "MassExport";

global string $AdvSkeleton[] = {"DeformationSystem","Geometry","FaceDeformationSystem"};

global int $AdvNumber[] = {17,8,21};

global string $ListConstraint[] = {"parentConstraint","scaleConstraint","pointConstraint","orientConstraint"};

global string $AdvDeletedObject[] = {"FaceFitSkeleton","FitSkeleton","FaceMotionSystem","MotionSystem"};

global string $BaseSkeletals[];

global string $FbxOpt= "%2";
global string $Mesh = "%3";

proc int LObjectExists(string $inobjectname)
{
	return `objExists $inobjectname`;
}

proc int LGetStartFrame(string $inLayerExp)
{
	if(!`objExists $inLayerExp`){
		return -1;
	};

	if(attributeExists("FrameRange",$inLayerExp))
		return int(`addAttr -q  -min ($inLayerExp+".FrameRange")`);
	
	return int(`playbackOptions -q -min`);
}

proc int LGetEndFrame(string $inLayerExp){
	if(!`objExists $inLayerExp`){
		return -1;
	};

	if(attributeExists("FrameRange",$inLayerExp))
		return int(`addAttr -q  -max ($inLayerExp+".FrameRange")`);
	return int(`playbackOptions -q -max`);;
}

proc LClearContraints(string $inContraitName){
	if($inContraitName =="") return;

	string $Cons[] = `ls -typ $inContraitName`;

	if(size($Cons) <=0) return;

	for($i = 0 ; $i < size($Cons) ; ++$i)
	{
		catch(`delete $Cons[$i]`);
	}

	print("Completed Clear : " + $inContraitName + "\n\n");
}

proc string[] LSplitString(string $inStr){

	string $buffer[];
	$numTokens = `tokenize $inStr ":" $buffer`;
	return $buffer;
}
 
proc LClearListSet()
{
	string $ListSets[] = `ls -sets`;
	if(size($ListSets) <= 0) return;

	string $CantDelete[] = {"defaultLightSet","defaultObjectSet","initialParticleSE","initialShadingGroup"};

	for($i = 0 ; $i< size($ListSets);++$i){
		int $isDelete=0;
		for($x = 0 ; $x < size($CantDelete) ; ++$x)
		{	
			if($ListSets[$i]==$CantDelete[$x])
				$isDelete = 1;
		}

		if($isDelete==0){
			if(`objExists $ListSets[$i]`)
				catch(`delete $ListSets[$i]`);
		}
	}
}

proc string[] LGetAllJointInGrp(string $inGrpName)
{
	string $results[];
	if (LObjectExists($inGrpName))
		return $results = `listRelatives -ad -typ "joint" $inGrpName`;

	return $results;
}

proc LBakeFunc()
{
	global string $MassFbxLayer;
	int $Stime = `playbackOptions -q -min`;
	int $Etime = `playbackOptions -q -max`;
	playbackOptions -min $Stime;
	playbackOptions -max $Etime;
	string $joints[] = `ls -typ "joint"`;//LGetAllJointInGrp($inGrpName);
	if (size($joints) <= 0) return;
	string $timeRange = $Stime + ":" + $Etime;
	select -r $joints;
	//print(`ls -sl`);
	bakeSimulation -t $timeRange;
	//bakeResults -simulation on -t $timeRange $joints;
	print("===========================BAKE DONE=======================\n");

}

proc ImportRef()
{
	string $ref[] = `ls -typ "reference"`;
	if(size($ref) <=0) return;

	for($i =0 ; $i < size($ref) ; ++$i)
	{
		//print($ref[$i] + "\n");
		string $file;
		catch($file =`referenceQuery -f $ref[$i]`);
		catch(`file -ir $file`);
	}
}


proc LClearAdvanceSkeleton(string $inAdvGrp)
{
	if($inAdvGrp=="") return;

	global string $AdvDeletedObject[];

	select -r $inAdvGrp;
	string $sel[] = `ls -sl`;
	string $trans[] = `listRelatives -ad -type "transform" $sel[0]`;

	for($i = 0 ; $i < size($trans); ++$i)
	{
		string $Splits[] = LSplitString($trans[$i]);
		for($a = 0 ; $a < size($AdvDeletedObject); ++$a)
		{
			if($Splits[size($Splits)-1] == $AdvDeletedObject[$a]){
				//print($Splits[size($Splits)-1] + "\n");
				//print($trans[$i] + "\n");
				if(LObjectExists($trans[$i])){
					//print("Optimize : "  + $trans[$i]+"\n");
					catch(`delete $trans[$i]`);
				}
			}
		}

	}

}

proc string[] LAdvanceSkeletonGeoJoint(string $inAdvGrp,int $Opt){
	
	string $results[];

	if($inAdvGrp=="") return $results;

	global string $AdvSkeleton[];
	global int $AdvNumber[];

	select -r $inAdvGrp;
	string $sel[] = `ls -sl`;
	string $trans[] = `listRelatives -ad -type "transform" $sel[0]`;
	
	int $count=0;
	for($i = 0 ; $i < size($trans); ++$i)
	{
		//string $Splits[] = LSplitString($trans[$i]);
		for($a = 0 ; $a < size($AdvSkeleton); ++$a)
		{
			string $endStr = endString($trans[$i],$AdvNumber[$a]);
			if($endStr == $AdvSkeleton[$a]){
				if($Opt == 1 && $AdvSkeleton[$a] == "Geometry")
					continue;
				$results[$count] = $trans[$i];
				$count++;
			}
		}

	}
	return $results;
}

proc string[] LObjectTypeFilter(string $inTopNode,string $inTypeNode){
	
	string $results[];

	if($inTopNode=="") return $results;

	return `listRelatives -ad -type $inTypeNode $inTopNode`;

}

proc string GetMassExportLayer()
{
    string $Layer[] = `ls -typ "displayLayer"`;
    
    for($i = 0 ; $i < size($Layer) ; ++$i){
        string $result = `tolower $Layer[$i]`;
        if($result =="massexport")
            return $Layer[$i];
    }
    return "None";
}

proc LCleanUnknownP(){
	string $unks[] = `unknownPlugin -q -l`;

	for($plugin in $unks){
		if($plugin !="redshift4maya"){
			catch(`unknownPlugin -r $plugin`);
			print("delete : " + $plugin + "\n");
		}
	}
}

proc LCleanUnknowNode(){
	string $nodes[] = `ls -typ "unknown"`;

	for($node in $nodes)
	{
		catch(`lockNode -l off $node`);
		catch(`delete $node`);
		print("delete unknowNode : " + $node + "\n");
	}
}

proc LCleanUpDisplayLayer()
{
	string $layers[] = `ls -typ "displayLayer"`;

	for($layer in $layers)
		if($layer != "defaultLayer")
			delete $layer;
}

proc LCleanUpFiles(){

	global string $ListConstraint[];

	//===========================CleanUp Scene============================
	print("=============================CleanUp Scene====================================\n");
	cleanUpScene(3);
	//===========================BAKE ANIM===========================
	print("===========================DELETE CONTRAINS=======================\n");
	LBakeFunc();
	//===========================REF IMPORT===========================
	//ImportRef();
	//===========================DELETE CONTRAINS=====================
	print("===========================DELETE CONTRAINS=======================\n");
	for($i = 0 ; $i < size($ListConstraint) ; ++$i)
		LClearContraints($ListConstraint[$i]);
	
	//===========================Clear unknowNode============================
	print("=============================Clear unknowNode=============================\n");
	LCleanUnknowNode();

	//===========================Remove unknowPlugins============================
	print("=============================Remove unknowPlugins=============================\n");
	LCleanUnknownP();

	//===========================Clear Sets============================
	print("=============================Clear Sets=============================\n");
	//LClearListSet();

}

proc string GetRefFile(string $inRefObject){

	string $fResult="";
	if(!`objExists $inRefObject` || !`referenceQuery -isNodeReferenced $inRefObject`) 
	{
		print("Object Not Found  : " + $inRefObject + "\n");
		return $fResult;
	}

	return `referenceQuery -filename $inRefObject`;

}

global proc LExportReferenceFile(string $inFile, string $inSelectObj)
{

	string $Split[] = LSplitString($inSelectObj);

	if($inFile == "") return;

	file -f -options "v=0;" -esn false  -ignoreVersion  -typ "mayaAscii" -o $inFile;
	//evalDeferred("select -r " + $Split[1] + ";");
	print("Open Base Skeletal  : " + $inFile + "\n");
	string $Advs[] = LAdvanceSkeletonGeoJoint($Split[1],2);
	select -cl;
	string $bMesh[]= `ls -typ "mesh"`;
	select -r $Advs;

	catch(`select -add $bMesh`);
	//file path
	string $exp = "%1" + "BaseSkeletal/" + $Split[0] + ".fbx" ;

	// Execute Export
	catch(`FBXExport -f $exp -s`);
	if(`file -q -ex $exp`)
		print("Exported : " + $exp + "\n");

}

proc int LGetFbxOpt()
{
	global string $FbxOpt;

	global string $MassFbxLayer;
	int $Stime = `playbackOptions -q -min`;
	int $Etime = `playbackOptions -q -max`;


	FBXExportCameras -v true;
	//FBXExportShapes -v true;
	FBXExportInputConnections -v false;
	FBXExportSkeletonDefinitions -v true;
	FBXExportSkins -v true;
	FBXExportScaleFactor 1.0;
	FBXExportAnimationOnly -v false;
	FBXExportBakeComplexAnimation -v false;
	FBXExportBakeComplexStart -v $Stime;
	FBXExportBakeComplexEnd -v $Etime;
	FBXExportBakeResampleAnimation -v false;
	FBXExportFileVersion -v `FBXExportFileVersion -q`;

	if($FbxOpt == "AnimOnly"){
		return 1;
	}
	else if($FbxOpt == "BaseSkeleton"){
		FBXExportBakeComplexAnimation -v false;
		return 2;
	}

	return 0;
}

global proc FbxExecute()
{
	global string $MassFbxLayer;
	global string $FbxOpt;
	global string $BaseSkeletals[];
	global string $Mesh;

	string $reffiles[];
	string $layerExp = GetMassExportLayer();
	string $MassExp[] = `editDisplayLayerMembers -q $layerExp`;
	string $MassExpFull[] = `editDisplayLayerMembers -q -fn $layerExp`;

	if(size($MassExp) <= 0) return;

	int $Opt = LGetFbxOpt();

	if($FbxOpt !="BaseSkeleton")
		ImportRef();

	//Log List File Export
	for($i = 0 ; $i < size($MassExp) ; ++$i){
		string $Str[] = LSplitString($MassExp[$i]);
		string $exp = "%1" + $Str[0] + ".fbx" ;
		print("ListFbx : " + $exp + "\n");
		if($FbxOpt == "BaseSkeleton")
		{
			string $baseFbx = GetRefFile($MassExp[$i]);
			if($baseFbx !="")
				print("ListFbx : " + $baseFbx + "\n");
		}
	}

	//clean up file
	LCleanUpFiles();
	LCleanUpDisplayLayer();

	int $addMesh =1;
	if($Mesh =="On"){
		$addMesh =2;
	}

	FBXExportShapes -v false;


	for($i = 0 ; $i < size($MassExp) ; ++$i)
	{
		select -cl;
		catch(`select -r $MassExpFull[$i]`);
		//===========================CLEAR ADVANSKELETON=====================
		LClearAdvanceSkeleton($MassExp[$i]);

		string $Str[] = LSplitString($MassExp[$i]);
		string $exp = "%1" + $Str[0] + ".fbx" ;
		
		
		string $GeoJnt[] = LAdvanceSkeletonGeoJoint($MassExp[$i],$addMesh);
		select -r $GeoJnt;

		if(size(`ls -sl`) <= 0)
			catch(`select -add $MassExpFull[$i]`);
		
		catch(`FBXExport -f $exp -s`);
		if($Opt==2){
			$BaseSkeletals[$i] = $MassExp[$i];
			$reffiles[$i] = GetRefFile($MassExp[$i]);
		}

		if(`file -q -ex $exp`)
			print("Exported : " + $exp + "\n");
	}

	if($FbxOpt == "BaseSkeleton"){
		int $f=0;
		FBXExportShapes -v true;
		for($Base in $BaseSkeletals){
			if($reffiles[$f] !=""){
				evalDeferred("LExportReferenceFile(\"" + $reffiles[$f] + "\",\"" + $Base + "\");");
			}
			$f++;
		}
	}

}
evalDeferred("FbxExecute();");
