proc LCleanUnknownP(){
	string $unks[] = `unknownPlugin -q -l`;

	for($plugin in $unks){
		if($plugin !="redshift4maya"){
			catch(`unknownPlugin -r $plugin`);
			print("delete : " + $plugin + "\n");
		}
	}
}

proc LCleanUnknowNode(){
	string $nodes[] = `ls -typ "unknown"`;

	for($node in $nodes)
	{
		catch(`lockNode -l off $node`);
		catch(`delete $node`);
		print("delete unknowNode : " + $node + "\n");
	}
}

global proc PlusCleanUp()
{
	LCleanUnknownP();
	LCleanUnknowNode();
	evalDeferred("cleanUpScene(3);");
}

PlusCleanUp();