//Check Plugins
if(!`pluginInfo -q -l "fbxmaya"`)
	loadPlugin "fbxmaya";

global string $MassFbxLayer = "MassExport";

global string $AdvSkeleton[] = {"DeformationSystem","Geometry","FaceDeformationSystem"};

global string $ListConstraint[] = {"parentConstraint","scaleConstraint","pointConstraint","orientConstraint"};

global string $AdvDeletedObject[] = {"FaceFitSkeleton","FitSkeleton","FaceMotionSystem","MotionSystem"};

global string $FbxOpt= "%2";

proc int LObjectExists(string $inobjectname)
{
	return `objExists $inobjectname`;
}

proc int LGetStartFrame(string $inLayerExp)
{
	if(!`objExists $inLayerExp`){
		return -1;
	};

	if(attributeExists("FrameRange",$inLayerExp))
		return int(`addAttr -q  -min ($inLayerExp+".FrameRange")`);
	
	return int(`playbackOptions -q -min`);
}

proc int LGetEndFrame(string $inLayerExp){
	if(!`objExists $inLayerExp`){
		return -1;
	};

	if(attributeExists("FrameRange",$inLayerExp))
		return int(`addAttr -q  -max ($inLayerExp+".FrameRange")`);
	return int(`playbackOptions -q -max`);;
}

proc LClearContraints(string $inContraitName){
	if($inContraitName =="") return;

	string $Cons[] = `ls -typ $inContraitName`;

	if(size($Cons) <=0) return;

	for($i = 0 ; $i < size($Cons) ; ++$i)
	{
		catch(`delete $Cons[$i]`);
	}

	print("Completed Clear : " + $inContraitName + "\n\n");
}

proc string[] LSplitString(string $inStr){

	string $buffer[];
	$numTokens = `tokenize $inStr ":" $buffer`;
	return $buffer;
}
 
proc LClearListSet()
{
	string $ListSets[] = `ls -sets`;
	if(size($ListSets) <= 0) return;

	string $CantDelete[] = {"defaultLightSet","defaultObjectSet","initialParticleSE","initialShadingGroup"};

	for($i = 0 ; $i< size($ListSets);++$i){
		int $isDelete=0;
		for($x = 0 ; $x < size($CantDelete) ; ++$x)
		{	
			if($ListSets[$i]==$CantDelete[$x])
				$isDelete = 1;
		}

		if($isDelete==0){
			if(`objExists $ListSets[$i]`)
				catch(`delete $ListSets[$i]`);
		}
	}
}

proc string[] LGetAllJointInGrp(string $inGrpName)
{
	string $results[];
	if (LObjectExists($inGrpName))
		return $results = `listRelatives -ad -typ "joint" $inGrpName`;

	return $results;
}

proc LBakeFunc()
{
	global string $MassFbxLayer;
	int $Stime = LGetStartFrame($MassFbxLayer);
	int $Etime = LGetEndFrame($MassFbxLayer);
	playbackOptions -min $Stime;
	playbackOptions -max $Etime;
	string $joints[] = `ls -typ "joint"`;//LGetAllJointInGrp($inGrpName);
	if (size($joints) <= 0) return;
	string $timeRange = $Stime + ":" + $Etime;
	select -r $joints;
	//print(`ls -sl`);
	bakeSimulation -t $timeRange;
	//bakeResults -simulation on -t $timeRange $joints;
	print("===========================BAKE DONE=======================\n");

}

proc ImportRef()
{
	string $ref[] = `ls -typ "reference"`;
	if(size($ref) <=0) return;

	for($i =0 ; $i < size($ref) ; ++$i)
	{
		//print($ref[$i] + "\n");
		string $file = `referenceQuery -f $ref[$i]`;
		catch(`file -ir $file`);
	}
}


proc LClearAdvanceSkeleton(string $inAdvGrp)
{
	if($inAdvGrp=="") return;

	global string $AdvDeletedObject[];

	select -r $inAdvGrp;
	string $sel[] = `ls -sl`;
	string $trans[] = `listRelatives -ad -type "transform" $sel[0]`;

	for($i = 0 ; $i < size($trans); ++$i)
	{
		string $Splits[] = LSplitString($trans[$i]);
		for($a = 0 ; $a < size($AdvDeletedObject); ++$a)
		{
			if($Splits[size($Splits)-1] == $AdvDeletedObject[$a]){
				//print($Splits[size($Splits)-1] + "\n");
				//print($trans[$i] + "\n");
				if(LObjectExists($trans[$i])){
					//print("Optimize : "  + $trans[$i]+"\n");
					catch(`delete $trans[$i]`);
				}
			}
		}

	}

}

proc string[] LAdvanceSkeletonGeoJoint(string $inAdvGrp,int $Opt){
	
	string $results[];

	if($inAdvGrp=="") return $results;

	global string $AdvSkeleton[];

	select -r $inAdvGrp;
	string $sel[] = `ls -sl`;
	string $trans[] = `listRelatives -ad -type "transform" $sel[0]`;
	
	int $count=0;
	for($i = 0 ; $i < size($trans); ++$i)
	{
		string $Splits[] = LSplitString($trans[$i]);
		for($a = 0 ; $a < size($AdvSkeleton); ++$a)
		{
			if($Splits[size($Splits)-1] == $AdvSkeleton[$a]){
				if($Opt == 1 && $AdvSkeleton[$a] == "Geometry")
					continue;
				$results[$count] = $trans[$i];
				$count++;
			}
		}

	}
	return $results;
}

proc LCleanUnknownP(){
	string $unks[] = `unknownPlugin -q -l`;

	for($plugin in $unks){
		if($plugin !="redshift4maya"){
			catch(`unknownPlugin -r $plugin`);
			print("delete : " + $plugin + "\n");
		}
	}
}

proc LCleanUnknowNode(){
	string $nodes[] = `ls -typ "unknown"`;

	for($node in $nodes)
	{
		catch(`lockNode -l off $node`);
		catch(`delete $node`);
		print("delete unknowNode : " + $node + "\n");
	}
}

proc LCleanUpDisplayLayer()
{
	string $layers[] = `ls -typ "displayLayer"`;

	for($layer in $layers)
		if($layer != "defaultLayer")
			delete $layer;
}

proc LCleanUpFiles(){

	global string $ListConstraint[];

	//===========================CleanUp Scene============================
	print("=============================CleanUp Scene====================================\n");
	cleanUpScene(3);
	//===========================BAKE ANIM===========================
	print("===========================DELETE CONTRAINS=======================\n");
	LBakeFunc();
	//===========================REF IMPORT===========================
	ImportRef();
	//===========================DELETE CONTRAINS=====================
	print("===========================DELETE CONTRAINS=======================\n");
	for($i = 0 ; $i < size($ListConstraint) ; ++$i)
		LClearContraints($ListConstraint[$i]);
	
	//===========================Clear unknowNode============================
	print("=============================Clear unknowNode=============================\n");
	LCleanUnknowNode();

	//===========================Remove unknowPlugins============================
	print("=============================Remove unknowPlugins=============================\n");
	LCleanUnknownP();

	//===========================Clear Sets============================
	print("=============================Clear Sets=============================\n");
	//LClearListSet();

}

proc int LGetFbxOpt()
{
	global string $FbxOpt;

	global string $MassFbxLayer;
	int $Stime = LGetStartFrame($MassFbxLayer);
	int $Etime = LGetEndFrame($MassFbxLayer);

	FBXExportCameras -v true;
	FBXExportInputConnections -v true;
	FBXExportShapes -v true;
	FBXExportSkeletonDefinitions -v true;
	FBXExportSkins -v true;
	FBXExportScaleFactor 1.0;
	FBXExportAnimationOnly -v false;
	FBXExportBakeComplexAnimation -v true;
	FBXExportBakeComplexStart -v $Stime;
	FBXExportBakeComplexEnd -v $Etime;
	FBXExportBakeResampleAnimation -v true;
	FBXExportFileVersion -v FBX202000;

	if($FbxOpt == "AnimOnly"){
		return 1;
	}
	else if($FbxOpt == "BaseSkeleton"){
		FBXExportBakeComplexAnimation -v false;
		return 2;
	}
	else if($FbxOpt == "All"){
		FBXExportBakeComplexAnimation -v true;
		return 3;
	}


	return 0;
}

global proc FbxExecute()
{
	global string $MassFbxLayer;
	global string $FbxOpt;

	string $MassExp[] = `editDisplayLayerMembers -q $MassFbxLayer`;
	if(size($MassExp) <= 0) return;

	LCleanUpFiles();


	int $Opt = LGetFbxOpt();

	int $Boolean = $Opt == 1 ? 1 : 0;
	LCleanUpDisplayLayer();

	for($i = 0 ; $i < size($MassExp) ; ++$i)
	{
		select -cl;
		select -r $MassExp[$i];
		//===========================CLEAR ADVANSKELETON=====================
		LClearAdvanceSkeleton($MassExp[$i]);

		
		string $Str[] = LSplitString($MassExp[$i]);
		string $exp = "%1" + $Str[0] + ".fbx" ;
		
		string $GeoJnt[] = LAdvanceSkeletonGeoJoint($MassExp[$i],$Opt);
		for($jnt in $GeoJnt)
			print($jnt + " :InfoLee\n");

		select -r $GeoJnt;

		if($Opt == 1)
		{
			string $Jnts[]= `listRelatives -ad -typ "joint" $MassExp[$i]`;
			if(size($Jnts) <= 0) continue;	
		}
		else if(size($GeoJnt) < 2)
			catch(`select -add $MassExp[$i]`);
		
		//catch(`delete ($Str[0] + ":MainSystem")`);
		catch(`FBXExport -f $exp -s`);

		if(`file -q -ex $exp`)
			print("Exported : " + $exp + "\n");
	}
}


//FbxExecute();

proc LExportReferenceFile(string $inSelectObj)
{
	if(!`objExists $inSelectObj` || 
	!`referenceQuery -isNodeReferenced $inSelectObj`
	) return;

	//int $Opt = LGetFbxOpt();

	string $Split[] = LSplitString($inSelectObj);
	string $file = `referenceQuery -filename $inSelectObj`;
	string $shortName = `referenceQuery -namespace -shortName $inSelectObj`;
	file -f -options "v=0;"  -ignoreVersion  -typ "mayaAscii" -o $file;
	//evalDeferred("select -r " + $Split[1] + ";");
	
	string $Advs[] = LAdvanceSkeletonGeoJoint($Split[1],2);
	select -cl;
	select -r $Advs;

	//file path
	string $exp = "C:/Users/thang/Documents/Exports/Base/" + $Split[0] + ".fbx" ;
	catch(`FBXExport -f $exp -s`);

	print($Advs);
}

LExportReferenceFile("Cudan01:Group");
//LCleanUnknowNode();
//cleanUpScene(3);

//file -f -options "v=0;"  -ignoreVersion  -typ "mayaAscii" -o "C:/Users/thang/Desktop/PlusAbc/_MODEL3D/2024_KunGalaxy/Character/Cudan_01/Cudan01_Rig.ma"