//commandPort -name "localhost:7001" -sourceType "mel" -echoOutput;


proc LeeMotionPath()
{
    string $sel[] = `ls -sl`;

    for($i = 0 ; $i < size($sel) -1;++$i)
    {
        string $CrvShape[] = `listRelatives -s $sel[0]`;

        string $pointOnCrv = `createNode "nearestPointOnCurve"`;

        connectAttr -f  ($CrvShape[0] + ".worldSpace[0]")  ($pointOnCrv + ".inputCurve");
        connectAttr -f  ($sel[$i+1] + ".translate")  ($pointOnCrv + ".inPosition");

        int $startTime = `playbackOptions -query -minTime`;
        int $endTime = `playbackOptions -query -maxTime`;

        select -cl ;
        select -r $sel[$i+1] $sel[0];

        float $pos = `getAttr ($pointOnCrv + ".result.parameter")`;
        string $motionPath = `pathAnimation -fractionMode false -follow true -followAxis x -upAxis z -worldUpType "vector" -worldUpVector 0 1 0 -inverseUp false -inverseFront false -bank false -startTimeU $startTime -endTimeU $endTime `;

        disconnectAttr ( $motionPath + "_uValue.output") ($motionPath + ".uValue");

        setAttr ($motionPath + ".uValue") $pos;

        delete $pointOnCrv;
    }

}

LeeMotionPath();